### ISSUE TITLE
Update CAS.CommServer.UA.ConfigurationEditor.ServerConfiguration

### ISSUE THREAD

**Issue by mpostol** [mpostol/OPCUA.Server.ConfigEditor#11]
The current version is incompatible with the ASMD.

## Tasks

- [x] update all NuGet packages
- [x] Fix UT
- [x] Generate the plugin
- [x] Copy the plugin to the ASMD embedded example.
